# Generated by Django 6.0.5 on 2026-05-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='positive_replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='total_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='total_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
