# Generated by Django 6.0.5 on 2026-05-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
