# Generated by Django 6.0.5 on 2026-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_emaillog_is_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
